### ISSUE TITLE
Possible to await completion of SerialTaskManager tasks?

### ISSUE THREAD

**Issue by tfe** [robertmryan/SerialTasks#1]
Hi, thanks for answering these questions on SO and publishing this demo! Having it in the form of this repo was super-helpful.

I was wondering if it is possible to accomplish this scenario... say I am doing something similar to how you call `experiment()` in the demo, but I had something I wanted to run only after the experiment is finished:

```swift
print("Starting experiment")
await experiment()
print("Finished experiment")
workThatExpectsExperimentToBeFinished()
```

This executes in this order:

```
Starting experiment
updateA started
Finished experiment
updateA ended
updateA started
updateA ended
updateB started
updateB ended
updateC started
updateC ended
updateA started
updateA ended
```

Is there any way to actually await completion of the work done inside `experiment()`? The `await` made me think this would Just Work, but then I realized that `await` is just for the addition of the tasks to the SerialTaskManager.

The only idea I had was something like the following; it does actually work in terms of achieving the desired execution order but it's very clumsy and totally defeats the elegance of async/await:

```swift
    func experiment(afterExperiment: @Sendable @escaping () async throws -> Void) async {
        let taskManager = SerialTaskManager()
        await taskManager.add { await updateA() }
        await taskManager.add { await updateA() }
        await taskManager.add { await updateB() }
        await taskManager.add { await updateC() }
        await taskManager.add { await updateA() }
        await taskManager.add(block: afterExperiment)
    }

    print("Starting experiment")
    await experiment(afterExperiment: {
        print("Finished experiment")
        workThatExpectsExperimentToBeFinished()
    })
```

I am very new to async/await so I'm hoping there is something obvious that I'm missing but would be quick and easy for you to point out. Thanks for taking the time to read.

**Comment by robertmryan** [comment]
You can `await` the `add` function. See [this commit](https://github.com/robertmryan/SerialTasks/commit/d1aa0f314ab9b0b3d14873f462c5ed20c7f4d0b0#diff-8ef8aa849ddc19bede496b72d4decf1858bfd97f05b672f27265311b77b5edcdR20).

I should mention, though, while this “await prior task” pattern works, I have increasingly shifted to `AsyncSequence` (e.g. `AsyncStream` or `AsyncChannel`) for serial execution. It keeps you within the realm of structured concurrency.

See https://stackoverflow.com/a/75730483/1271826 or https://stackoverflow.com/a/73072799/1271826.

**Comment by tfe** [comment]
Thanks Rob, I really appreciate you taking the time to respond! That solves my problem.

I did take a crack at switching my implementation to using `AsyncChannel` after reading your SO answers. I ran into trouble in a couple places. Can you let me know if I'm missing a way to accomplish the following using the `AsyncChannel` approach (or `AsyncThrowingChannel` in the case of #2)?

1. Using the context of the SerialDownloadManager, is it possible to append a set of URLs and await the completion of their downloading? Similar to my original question, if I had work that needed to run after the downloads were finished? In my (admittedly limited) experimentation, appending the URLs seemed to continue execution immediately.

2. Let's say I wanted to handle exceptions thrown during the download... it seems like those would be thrown from `startDownloader()` rather than where I'd want to handle them: at the point I enqueue the download.

**Comment by robertmryan** [comment]
With `AsyncChannel` it returns when the `for`-`await`-`in` loop pulls a sent value from the channel. So, the code that does the `send` of the `URL` will only `await` the starting of that request, not its completion.

This is kludgy, but if doing a serial `AsyncChannel`, you could use an enumeration, though:

```swift
actor Downloader {
    var channel = AsyncChannel<DownloaderAction>()

    func startDownloader() async {
        for await action in channel {
            if case .request(let url) = action {
                await download(url)
            }
        }
    }

    func downloadAll(_ urls: [URL]) async {
        for url in urls {
            await send(url)
        }

        await finished()              // because `startDownloader` has an `await` for each action, you won't get here until all the downloads are done (because we're doing them sequentially)
    }
}

private extension Downloader {
    func send(_ url: URL) async {
        await channel.send(.request(url))
    }

    func finished() async {
        await channel.send(.finished)
    }

    func download(_ url: URL) async { … }
}

enum DownloaderAction {
    case request(URL)
    case finished
}
```

It gets more complicated in the non-serial constrained concurrency scenario. In that case, I might just give up on `AsyncChannel` and use a different task group for every batch of downloads:

```swift
func download(_ urls: [URL]) async {
    await withTaskGroup(of: Void.self) { group in
        for (index, url) in urls.enumerated() {
            if index > 4 { await group.next() }

            group.addTask { await self.download(url) }
        }
    }
}
```

You can’t add more URLs to the previous download batch, though.

I wish actors had the concept of advanced reentrancy constraints (max concurrency, barrier-like behavior, etc.), but they don’t (and I am not optimistic that we’ll see that anytime soon).

**Comment by tfe** [comment]
Hi Rob, thanks for taking the time to think through this and explain. `AsyncChannel` is starting to feel like even more of a square-peg-round-hole situation than the previous solution of awaiting the previous task. I think I'm going to end up going with that as the least-bad fit, and see how that works in practice. Hopefully it holds up long enough for Swift Concurrency to gain some additional features that make this kind of workload easier to model.

Thanks again for your time working through this with me. I appreciate it!
